version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - "./:/app/"
    tty: true
    command: "python src/main.py"
